name: TEST Android Build
on:
    workflow_dispatch:
    release:
        types: [published] # only run the workflow when a new release has been published
jobs:
    android-build:
        name: Android Build
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Set up our JDK environment
              uses: actions/setup-java@v3
              with:
                  java-version: "17"

            - name: Install dependencies
              run: npm ci

            - name: Cache Gradle Wrapper
              uses: actions/cache@v3
              with:
                  path: ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

            - name: Cache Gradle Dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-caches-

            - name: Make Gradlew Executable
              run: cd android && chmod +x ./gradlew

            - name: Generate App APK
              run: |
                  cd android && ./gradlew assembleRelease --no-daemon

            - name: Sign APK
              id: sign_app
              uses: r0adkll/sign-android-release@v1
              with:
                  releaseDirectory: android/app/build/outputs/apk/release
                  signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
                  alias: ${{ secrets.ANDROID_ALIAS }}
                  keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}

            - name: upload artifact to Firebase App Distribution
              uses: wzieba/Firebase-Distribution-Github-Action@v1
              with:
                  appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}
                  token: ${{secrets.ANDROID_FIREBASE_TOKEN}}
                  groups: testers
                  file: ${{steps.sign_app.outputs.signedReleaseFile}}
